### ISSUE TITLE
Travis.genkeys error

### ISSUE THREAD

**Issue by Ward9250** [JuliaDocs/Documenter.jl#335]
Hi, I'm trying to get documentation set up for: https://github.com/BioJulia/WAHVectors.jl

```julia
julia> using Documenter

julia> Pkg.clone("https://github.com/BioJulia/WAHVectors.jl.git")
INFO: Cloning WAHVectors from https://github.com/BioJulia/WAHVectors.jl.git
INFO: Computing changes...

julia> Travis.genkeys("WAHVectors")
Generating public/private rsa key pair.
Your identification has been saved in .documenter.
Your public key has been saved in .documenter.pub.
The key fingerprint is:
SHA256:rDzcViYoDvy871LcKPNKo81Mg/ahJmhjMUydgQ42mjQ axolotlfan9250@Bens-MacBook-Pro.local
The key's randomart image is:
+---[RSA 2048]----+
|  .              |
|.E .             |
|*.+ o            |
|o+ o   o         |
|o o ...oS o      |
| + *o++o.+       |
|. = X== o        |
|o=.X.=.o         |
|oo+ B=o          |
+----[SHA256]-----+
We need your GitHub login to identify you.
This information will not be sent to Travis CI, only to api.github.com.
The password will not be displayed.

Try running with --github-token or --auto if you don't want to enter your password anyway.

Username: Ward9250
Password for Ward9250: ********secretstuff********
Two-factor authentication code for Ward9250: ********secretstuff********
Validation Failed
for a full error report, run travis report
ERROR: failed process: Process(`travis login --auto`, ProcessExited(1)) [1]
 in pipeline_error(::Base.Process) at ./process.jl:616
 in run at ./process.jl:592 [inlined]
 in (::Documenter.Travis.##2#3{String})() at /Users/axolotlfan9250/.julia/v0.5/Documenter/src/Documenter.jl:545
 in cd(::Documenter.Travis.##2#3{String}, ::String) at ./file.jl:59
 in #genkeys#1(::String, ::Function, ::String) at /Users/axolotlfan9250/.julia/v0.5/Documenter/src/Documenter.jl:533
 in genkeys(::String) at /Users/axolotlfan9250/.julia/v0.5/Documenter/src/Documenter.jl:522

shell> travis report
System
Ruby:                     Ruby 2.3.1-p112
Operating System:         Mac OS X 10.12
RubyGems:                 RubyGems 2.6.8

CLI
Version:                  1.8.2
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2016-10-31 23:34:53 +0000

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (current)

Last Exception
An error occurred running `travis login`:
    RuntimeError: Validation Failed
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/tools/github.rb:216:in `rescue in basic_auth'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/tools/github.rb:208:in `basic_auth'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/tools/github.rb:214:in `rescue in basic_auth'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/tools/github.rb:208:in `basic_auth'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/tools/github.rb:221:in `login'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/tools/github.rb:80:in `possible_tokens'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/tools/github.rb:49:in `each_token'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/tools/github.rb:36:in `with_token'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/cli/login.rb:31:in `login'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/cli/login.rb:40:in `run'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/cli/command.rb:198:in `execute'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/cli.rb:64:in `run'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:22:in `load'
        from /usr/local/bin/travis:22:in `<main>'


For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

Is there a way to get going without the gem? I don't remember going through this when I set up BioJulia/Bio.jl's doc building.

**Comment by ChrisRackauckas** [comment]
I am running into this too. This is why I am still asking for the documentation which doesn't require a local travis to come back. See https://github.com/JuliaDocs/Documenter.jl/issues/298 .

**Comment by ChrisRackauckas** [comment]
```julia
julia> using Documenter

julia> Travis.genkeys("DiffEqDocs")
Generating public/private rsa key pair.
.documenter already exists.
Overwrite (y/n)? y
Your identification has been saved in .documenter.
Your public key has been saved in .documenter.pub.
The key fingerprint is:
be:d5:f6:ed:2d:e6:c9:7c:03:1f:15:7b:e7:a4:84:15 crackauc@crackauc2
The key's randomart image is:
+--[ RSA 2048]----+
|              E. |
|              .. |
|             o  o|
|            . ..=|
|        S    . ++|
|       .   . ....|
|        . . o o .|
|         o . +o=o|
|        .    o*+=|
+-----------------+
We need your GitHub login to identify you.
This information will not be sent to Travis CI, only to api.github.com.
The password will not be displayed.

Try running with --github-token or --auto if you don't want to enter your password anyway.

Username: ChrisRackauckas
Password for ChrisRackauckas: ***********
Two-factor authentication code for ChrisRackauckas: 443939
Validation Failed
for a full error report, run travis report
ERROR: failed process: Process(`travis login --auto`, ProcessExited(1)) [1]
 in run at ./process.jl:592 [inlined]
 in (::Documenter.Travis.##2#3{String})() at /home/crackauc/.julia/v0.5/Documenter/src/Documenter.jl:545
 in cd(::Documenter.Travis.##2#3{String}, ::String) at ./file.jl:59
 in #genkeys#1(::String, ::Function, ::String) at /home/crackauc/.julia/v0.5/Documenter/src/Documenter.jl:533
 in genkeys(::String) at /home/crackauc/.julia/v0.5/Documenter/src/Documenter.jl:522
 in eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:64
 in macro expansion at ./REPL.jl:95 [inlined]
 in (::Base.REPL.##3#4{Base.REPL.REPLBackend})() at ./event.jl:68
```

**Comment by MichaelHatherly** [comment]
`travis` is a bit of a pain to get working correctly. I'll try come up with an alternative approach &mdash; probably just using `openssl` directly to encrypt and decrypt the private key.

**Comment by Ward9250** [comment]
I think when I did it for Bio.jl, I just had to give the travis repo a github token or some such thing, can't fully remember now as it was some time ago.

**Comment by MichaelHatherly** [comment]
Yes, we used to use `GITHUB_API_KEY` tokens, but that gives travis access to all the repos associated with a user/org, hence why we've moved to using ssh keys that only give access to a single repo at a time.

**Comment by MichaelHatherly** [comment]
Fixed by https://github.com/JuliaDocs/Documenter.jl/pull/336.
