### ISSUE TITLE
mkdocs version conflict.

### ISSUE THREAD

**Issue by ken-roberts** [JuliaDocs/Documenter.jl#832]
Hi,

I have EXACTLY this problem: https://github.com/JuliaDocs/Documenter.jl/issues/590

I'm on Ubuntu 18.04, and I completely uninstalled mkdocs-materials-components, mkdocs-materials and mkdocs. I went to ~/.local/lib/python2.7/site-packages and removed both directories that were still hanging around, with mkdocs as the first part of the directory name.

I did this:
```pip install mkdocs
mkdocs --version                       # gets me 1.0.4
pip install mkdocs-material
mkdocs --version                       # still 1.0.4
pip install mkdocs-material-components
mkdocs --version                       # gets me 0.16.3
mkdocs serve
INFO    -  Building documentation...                                                   
Traceback (most recent call last):
  File "/home/ken/.local/bin/mkdocs", line 11, in <module>                                
    sys.exit(cli())                                                      
  File "/home/ken/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)                           
  File "/home/ken/.local/lib/python2.7/site-packages/click/core.py", line 697, in main                                           
    rv = self.invoke(ctx)             
  File "/home/ken/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ken/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ken/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)     
  File "/home/ken/.local/lib/python2.7/site-packages/mkdocs/__main__.py", line 127, in serve_command
    livereload=livereload                                          
  File "/home/ken/.local/lib/python2.7/site-packages/mkdocs/commands/serve.py", line 110, in serve
    config = builder()                                   
  File "/home/ken/.local/lib/python2.7/site-packages/mkdocs/commands/serve.py", line 101, in builder
    theme_dir=theme_dir                                    
  File "/home/ken/.local/lib/python2.7/site-packages/mkdocs/config/base.py", line 181, in load_config
    errors, warnings = cfg.validate()                          
  File "/home/ken/.local/lib/python2.7/site-packages/mkdocs/config/base.py", line 105, in validate
    post_failed, post_warnings = self._post_validate()       
  File "/home/ken/.local/lib/python2.7/site-packages/mkdocs/config/base.py", line 85, in _post_validate
    config_option.post_validation(self, key_name=key)             
  File "/home/ken/.local/lib/python2.7/site-packages/mkdocs/config/config_options.py", line 288, in post_validation
    theme_dir = [utils.get_theme_dir(config['theme']), ]         
  File "/home/ken/.local/lib/python2.7/site-packages/mkdocs/utils/__init__.py", line 383, in get_theme_dir
    return os.path.dirname(os.path.abspath(theme.load().__file__))      
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2323, in load
    self.require(*args, **kwargs)                               
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2346, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (mkdocs 1.0.4 (/home/ken/.local/lib/python2.7/site-packages), Requirement.parse('mkdocs==0.16.3'))
```

I'm brand-new to mkdocs. I actually have mkdocs 0.16.3 in spite of the 1.0.4 current build, and for some reason it thinks I have 1.0.4.

Please help.

**Comment by ken-roberts** [comment]
Where do I put those dependencies?

I'm a complete n00b to mkdocs and python.

**Comment by mortenpi** [comment]
If you are doing things locally, then you should probably run something like:

```
pip install mkdocs==0.17.5
pip install mkdocs-material==2.9.4
```

If you are setting up `deploydocs` Travis deployment, then you should give the `deps` keyword with the value in the Discourse post to `deploydocs` (possibly removing some of the deps you do not actually need).
